### ISSUE TITLE
Template render error in tag endemoji in hexo 3.1.1

### ISSUE THREAD

**Issue by Eamonnzhang** [sergiolepore/hexo-tag-emojis#11]
> Template render error: unknown block tag: endemoji
    at Error.exports.TemplateError (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\lib.js:51:19)
    at Object.extend.fail (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:64:15)
    at Object.extend.parseStatement (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:544:18)
    at Object.extend.parseNodes (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:1151:30)
    at Object.extend.parseAsRoot (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:1177:42)
    at Object.module.exports.parse (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\parser.js:1199:18)
    at Object.module.exports.compile (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\compiler.js:1118:48)
    at Obj.extend._compile (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:444:35)
    at Obj.extend.compile (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:433:18)
    at null.<anonymous> (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:378:22)
    at Object.exports.withPrettyErrors (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\lib.js:24:16)
    at Obj.extend.render (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:374:20)
    at Obj.extend.renderString (F:\hexo_blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:261:21)
    at F:\hexo_blog\node_modules\hexo\lib\extend\tag.js:56:9
    at tryCatcher (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:70:37)
    at Tag.render (F:\hexo_blog\node_modules\hexo\lib\extend\tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (F:\hexo_blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at Promise.then.then.then.output (F:\hexo_blog\node_modules\hexo\lib\hexo\render.js:55:19)
    at tryCatcher (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Async.drainQueues (F:\hexo_blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:415:13)

**Comment by LionSR** [comment]
I met this problem too.

**Comment by Gtskk** [comment]
Maybe `endemoji-block` is the right end block tag name.

**Comment by tkirshboim** [comment]
@Gtskk that didn't work for me. The thing that did work was renaming the tag to `emoji_block`. See the [pull request](https://github.com/sergiolepore/hexo-tag-emojis/pull/12) I made.
It seems that `-` (minus sign) in the block name does not work anymore (?).
